"""add retrieval_stats to mission_analyses

Revision ID: 13325cb7782a
Revises: 2e7a9846de2e
Create Date: 2026-07-12 14:40:43.678870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13325cb7782a"
down_revision: str | Sequence[str] | None = "2e7a9846de2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mission_analyses",
        sa.Column("retrieval_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mission_analyses", "retrieval_stats")
    # ### end Alembic commands ###
