"""add mission_analyses table

Revision ID: 58ae864afad0
Revises: 2c4d6ce01b9b
Create Date: 2026-07-12 02:11:18.054329

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58ae864afad0"
down_revision: str | Sequence[str] | None = "2c4d6ce01b9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mission_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="analysis_status"),
            nullable=False,
        ),
        sa.Column("business_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("strategy_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risk_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("executive_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id"),
    )
    op.create_index(
        op.f("ix_mission_analyses_status"), "mission_analyses", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mission_analyses_status"), table_name="mission_analyses")
    op.drop_table("mission_analyses")
    # ### end Alembic commands ###
