import { useState } from 'react'
import {
  Briefcase,
  ChevronDown,
  Database,
  Gauge,
  GitBranch,
  Hash,
  Quote,
  ShieldAlert,
  Sparkles,
  Target,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import Badge from '../Badge'
import { confidenceBadgeVariant, confidenceLabel } from '../../utils/executiveDashboard'
import { evidenceQualityLabel, evidenceQualityVariant } from '../../utils/explainability'
import type { AgentName, ExplainabilityCard as ExplainabilityCardData } from '../../utils/explainability'

const AGENT_ICONS: Record<AgentName, LucideIcon> = {
  Business: Briefcase,
  Strategy: Target,
  Risk: ShieldAlert,
  Executive: Sparkles,
}

interface FieldProps {
  label: string
  value: string | null
}

function Field({ label, value }: FieldProps) {
  return (
    <div>
      <h4 className="text-xs font-semibold uppercase tracking-wide text-neutral-500 dark:text-neutral-400">{label}</h4>
      {value ? (
        <p className="mt-1 text-sm text-neutral-700 dark:text-neutral-300">{value}</p>
      ) : (
        <p className="mt-1 text-sm italic text-neutral-400 dark:text-neutral-600">Not Available</p>
      )}
    </div>
  )
}

function NotAvailableBadge() {
  return (
    <Badge variant="neutral" className="border border-dashed border-neutral-300 dark:border-neutral-700">
      Not Available
    </Badge>
  )
}

interface ExplainabilityCardProps {
  card: ExplainabilityCardData
  /** When true, renders permanently expanded with no click-to-toggle
   * affordance — used by the Executive Report, where an accordion default
   * of "collapsed" would print/export with the card's entire body (evidence,
   * reasoning, traceability) invisible, since nothing can click to expand a
   * printed page. Styling, spacing, badges, icons, and typography are
   * identical either way; only the interaction is removed. The
   * Explainability Center itself omits this prop, keeping its normal
   * click-to-expand behavior. */
  forceExpanded?: boolean
}

function ExplainabilityCard({ card, forceExpanded = false }: ExplainabilityCardProps) {
  const [expandedState, setExpandedState] = useState(false)
  const expanded = forceExpanded || expandedState
  const Icon = AGENT_ICONS[card.agentName]
  const panelId = `explainability-panel-${card.id}`

  const headerInner = (
    <>
      <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary-50 text-primary-600 dark:bg-primary-950/60 dark:text-primary-400">
        <Icon className="h-4 w-4" aria-hidden="true" />
      </span>
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-medium text-neutral-900 dark:text-neutral-100">{card.title}</p>
        <p className="mt-0.5 text-xs text-neutral-500 dark:text-neutral-400">Generated by {card.agentName} Agent</p>
      </div>
      <div className="hidden shrink-0 items-center gap-1.5 sm:flex">
        <Badge variant={confidenceBadgeVariant(card.confidencePercent / 100)}>
          {card.confidencePercent}% {confidenceLabel(card.confidencePercent / 100)}
        </Badge>
        <Badge variant={evidenceQualityVariant(card.evidenceCount)}>{evidenceQualityLabel(card.evidenceCount)}</Badge>
      </div>
      {!forceExpanded && (
        <ChevronDown
          className={`h-4 w-4 shrink-0 text-neutral-400 transition-transform duration-300 ${expanded ? 'rotate-180' : ''}`}
          aria-hidden="true"
        />
      )}
    </>
  )

  const bodyInner = (
    <>
      <div className="flex sm:hidden flex-wrap items-center gap-1.5">
        <Badge variant={confidenceBadgeVariant(card.confidencePercent / 100)}>
          {card.confidencePercent}% {confidenceLabel(card.confidencePercent / 100)}
        </Badge>
        <Badge variant={evidenceQualityVariant(card.evidenceCount)}>{evidenceQualityLabel(card.evidenceCount)}</Badge>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <Field label="Executive Summary" value={card.executiveSummary} />
        <Field label="Reasoning" value={card.reasoning} />
        <Field label="Business Impact" value={card.businessImpact} />
        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wide text-neutral-500 dark:text-neutral-400">
            Datasets Used
          </h4>
          {card.datasetsUsed.length > 0 ? (
            <div className="mt-1.5 flex flex-wrap gap-1.5">
              {card.datasetsUsed.map((name) => (
                <span
                  key={name}
                  className="inline-flex items-center gap-1 rounded-md bg-neutral-100 px-2 py-0.5 text-xs font-medium text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300"
                >
                  <Database className="h-3 w-3" aria-hidden="true" />
                  {name}
                </span>
              ))}
            </div>
          ) : (
            <p className="mt-1 text-sm italic text-neutral-400 dark:text-neutral-600">Not Available</p>
          )}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 rounded-lg bg-neutral-50 p-3 dark:bg-neutral-800/40 sm:grid-cols-5">
        <MiniStat icon={Hash} label="Chunk IDs" value={null} />
        <MiniStat icon={Gauge} label="Similarity Score" value={card.similarityScorePercent !== null ? `${card.similarityScorePercent}%` : null} />
        <MiniStat icon={Sparkles} label="Embedding Model" value={card.embeddingModel} />
        <MiniStat icon={Quote} label="Retrieved Evidence" value={String(card.evidenceCount)} />
        <MiniStat
          icon={Target}
          label="Evidence Coverage"
          value={card.evidenceCoveragePercent !== null ? `${card.evidenceCoveragePercent}%` : null}
        />
      </div>

      <div>
        <h4 className="mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-neutral-500 dark:text-neutral-400">
          <Quote className="h-3.5 w-3.5" aria-hidden="true" />
          Evidence Used
        </h4>
        {card.evidenceUsed.length > 0 ? (
          <ul className="flex flex-col gap-2">
            {card.evidenceUsed.map((item, index) => (
              <li
                key={index}
                className="flex gap-2 rounded-md border-l-2 border-primary-400 bg-neutral-900 px-3 py-2 font-mono text-xs text-neutral-100 dark:border-primary-600 dark:bg-black/40"
              >
                <span className="shrink-0 text-primary-400">[{index + 1}]</span>
                <span className="min-w-0 break-words">{item}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-sm italic text-neutral-400 dark:text-neutral-600">Not Available</p>
        )}
      </div>

      <div className="flex flex-col gap-2 border-t border-neutral-200 pt-4 dark:border-neutral-800 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex min-w-0 flex-wrap items-center gap-1 text-xs text-neutral-500 dark:text-neutral-400">
          <GitBranch className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
          {card.traceability.map((step, index) => (
            <span key={step} className="flex items-center gap-1">
              <span>{step}</span>
              {index < card.traceability.length - 1 && <span aria-hidden="true">→</span>}
            </span>
          ))}
        </div>
        <Badge variant="success">Agent Status: {card.agentStatus}</Badge>
      </div>
    </>
  )

  return (
    <div className="overflow-hidden rounded-lg border border-neutral-200 transition-colors dark:border-neutral-800">
      {forceExpanded ? (
        <div className="flex w-full items-center gap-3 bg-neutral-50 px-4 py-3 text-left dark:bg-neutral-800/40">{headerInner}</div>
      ) : (
        <button
          type="button"
          onClick={() => setExpandedState((prev) => !prev)}
          aria-expanded={expanded}
          aria-controls={panelId}
          className="flex w-full items-center gap-3 bg-neutral-50 px-4 py-3 text-left transition-colors hover:bg-neutral-100 dark:bg-neutral-800/40 dark:hover:bg-neutral-800"
        >
          {headerInner}
        </button>
      )}

      {forceExpanded ? (
        <div id={panelId} className="flex flex-col gap-5 border-t border-neutral-200 p-4 dark:border-neutral-800">
          {bodyInner}
        </div>
      ) : (
        <div
          id={panelId}
          className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${expanded ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}
        >
          <div className="overflow-hidden">
            <div
              className={`flex flex-col gap-5 border-t border-neutral-200 p-4 transition-opacity duration-300 dark:border-neutral-800 ${expanded ? 'opacity-100' : 'opacity-0'}`}
            >
              {bodyInner}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function MiniStat({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string | null }) {
  return (
    <div className="flex flex-col gap-1">
      <span className="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wide text-neutral-400 dark:text-neutral-500">
        <Icon className="h-3 w-3" aria-hidden="true" />
        {label}
      </span>
      {value ? (
        <span className="truncate text-xs font-medium text-neutral-900 dark:text-neutral-100" title={value}>
          {value}
        </span>
      ) : (
        <NotAvailableBadge />
      )}
    </div>
  )
}

export default ExplainabilityCard
